 FAIL  components/__tests__/auth/AuthContext.test.tsx
  ● Console

    console.log
      Current API_URL: https://137cc191-b824-40bd-89ee-eb24e7330321-00-qgvpjoy7e1af.worf.replit.dev:3001

      at Object.log (api/client.ts:16:9)

  ● AuthContext › should login successfully

    Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

      433 | };
      434 |
    > 435 | export const useAuth = () => useContext(AuthContext);
          |                                        ^

      at Object.throwInvalidHookError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5530:9)
      at useContext (node_modules/react/cjs/react.development.js:1618:21)
      at useAuth (contexts/AuthContext.tsx:435:40)
      at components/__tests__/auth/AuthContext.test.tsx:29:35
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12
      at callback (node_modules/@testing-library/react-native/src/act.ts:32:24)
      at act (node_modules/react/cjs/react.development.js:2512:16)
      at actImplementation (node_modules/@testing-library/react-native/src/act.ts:31:25)
      at Object.<anonymous> (components/__tests__/auth/AuthContext.test.tsx:28:14)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12)